C:\Ohjelmia\MSYS2\ucrt64\bin\g++.exe 
-g C:\Users\valas\VSCProjects\C_peli\Dailys\2_win32_window.cpp 
-o C:\Users\valas\VSCProjects\C_peli\Dailys\2_win32_window.exe 
-L C:\Windows\System32 -l gdi32 -l user32



Vai pitääkö olla polku compilerin kirjastoon?



C:\Ohjelmia\MSYS2\ucrt64\bin\g++.exe 
-g C:\Users\valas\VSCProjects\C_peli\Dailys\2_win32_window.cpp 
-o C:\Users\valas\VSCProjects\C_peli\Dailys\2_win32_window.exe 
-L C:\Ohjelmia\MSYS2\ucrt64\lib -l gdi32 -l user32

EI ERRORIA!½!



16.6.2025 Compiler settings now include -D to define variables in header


{
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\Ohjelmia\\MSYS2\\ucrt64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-L",
                "C:\\Ohjelmia\\MSYS2\\ucrt64\\lib",
                "-l",
                "gdi32",
                "-l",
                "user32",
                "-l",
                "onecore",
                "-D",           //-D to define things in header file
                "DEBUG_MODE=1"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }